<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.test.context.junit4.StandardJUnit4FeaturesSpringRunnerTests" tests="7" skipped="2" failures="0" errors="0" timestamp="2021-04-16T01:55:11" hostname="DESKTOP-3R4DVF7" time="0.004">
  <properties/>
  <testcase name="noOpShouldNotTimeOut" classname="org.springframework.test.context.junit4.StandardJUnit4FeaturesSpringRunnerTests" time="0.001"/>
  <testcase name="alwaysFailsButShouldBeIgnored" classname="org.springframework.test.context.junit4.StandardJUnit4FeaturesSpringRunnerTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="alwaysSucceeds" classname="org.springframework.test.context.junit4.StandardJUnit4FeaturesSpringRunnerTests" time="0.0"/>
  <testcase name="verifyBeforeClassAnnotation" classname="org.springframework.test.context.junit4.StandardJUnit4FeaturesSpringRunnerTests" time="0.0"/>
  <testcase name="verifyBeforeAnnotation" classname="org.springframework.test.context.junit4.StandardJUnit4FeaturesSpringRunnerTests" time="0.0"/>
  <testcase name="expectingAnIndexOutOfBoundsException" classname="org.springframework.test.context.junit4.StandardJUnit4FeaturesSpringRunnerTests" time="0.0"/>
  <testcase name="failedAssumptionShouldPrecludeImminentFailure" classname="org.springframework.test.context.junit4.StandardJUnit4FeaturesSpringRunnerTests" time="0.002">
    <skipped/>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
